### ISSUE TITLE
Support --machine-readable flag

### ISSUE THREAD

**Issue by conorsch** [kuboj/vagrant-portinfo#1]
Typically I want to access to the forwarded port information so that I can use it programatically. Adding support for [machine readable output](http://docs.vagrantup.com/v2/cli/machine-readable.html) via the `--machine-readable` flag would accomplish this in a manner consistent with how other Vagrant commands pass off information to external tools.

Currently the output from `vagrant-portinfo` looks like this:

```
server1 (84a1587) running
------------------------------------------------
guest: 22       host: 2201
guest: 8080     host: 8083
```

When it could look like this:

```
1436548109,server1,forwarded_port,22,2201
1436548109,server1,forwarded_port,8080,8083
```

You may wish to include protocols in the output for future-compatibility, but I generally assume tcp for my use cases.

**Comment by kuboj** [comment]
Good idea! I'll have a look into it once I'll have time, perhaps next week. It doesn't seem very complicated

**Comment by kuboj** [comment]
Hi conorsch,

I just released version 0.0.7 of `vagrant-portinfo` which supports `--machine-readable` flag. Can you, please, check it out and tell me what do you think?

Thanks!

**Comment by conorsch** [comment]
@kuboj Your implementation is _exactly_ how I envisioned it. Running 0.0.7 now, and I'll be able to grep for these values! Thank you for being so responsive to the feature request. 

For my own elucidation, was the only necessary change cae127f?

**Comment by kuboj** [comment]
I was happy to help!
And yes, after some digging in Vagrant internals (for example [here](https://github.com/mitchellh/vagrant/blob/master/plugins/commands/status/command.rb#L26)) I figured out that implementing `--machine-readable` is really simple :)
